name: Pull Request Analisys

on:
  pull_request:
    branches: [ master ]

jobs:
  dotnet-testing-pr:
    runs-on: ubuntu-latest
    env:
      PATS__0: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
